export const bankList = [
  { name: 'Ngân hàng TMCP Tiên Phong', shortened: 'TPB' },
  { name: 'Ngân hàng TMCP Phát Triển Thành Phố Hồ Chí Minh', shortened: 'HDB' },
  { name: 'Ngân hàng TM TNHH MTV Dầu Khí Toàn Cầu', shortened: 'GPB' },
  { name: 'Ngân hàng TMCP Kỹ thương Việt Nam', shortened: 'TCB' },
  { name: 'Ngân hàng TNHH MTV Hongleong Việt Nam', shortened: 'HLB' },
  { name: 'Ngân hàng TMCP Đại Dương', shortened: 'OJB' },
  { name: 'Ngân hàng TMCP Bảo Viêtô', shortened: 'BVB' },
  { name: 'Ngân hàng TMCP Quân Đội', shortened: 'MB' },
  { name: 'Ngân hàng TMCP Việt Nam Thịnh Vương', shortened: 'VPB' },
  { name: 'Ngân hàng TNHH MTV Public Việt Nam', shortened: 'PBVN' },
  { name: 'Ngân hàng TMCP Công Thương Việt Nam', shortened: 'CTG' },
  { name: 'Ngân hàng TMCP Xuất nhập khẩu Việt Nam', shortened: 'EIB' },
  { name: 'Ngân hàng TMCP Đông Nam Á', shortened: 'SEAB' },
  { name: 'Ngân hàng TMCP Sài Gòn', shortened: 'SCB' },
  { name: 'Ngân hàng TMCP Phương Đông', shortened: 'OCB' },
  { name: 'Ngân hàng TMCP An Bình', shortened: 'ABB' },
  { name: 'Ngân hàng TMCP Hàng Hải Việt Nam', shortened: 'MSB' },
  { name: 'Ngân hàng TMCP Việt Á', shortened: 'VAB' },
  { name: 'Ngân hàng TMCP Quốc Dân', shortened: 'NCB' },
  { name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', shortened: 'BIDV' },
  { name: 'Ngân hàng TMCP Sài Gòn - Hà Nội', shortened: 'SHB' },
  { name: 'Ngân hàng TMCP Đông Á', shortened: 'DongABank' },
  { name: 'Ngân hàng TMCP Quốc Tế', shortened: 'VIB' },
  { name: 'Ngân hàng TNHH MTV Shinhan Việt Nam', shortened: 'SHBVN' },
  { name: 'Ngân hàng TMCP Việt Nam Thương Tín', shortened: 'VIETBANK' },
  { name: 'Ngân hàng TMCP Bản Việt', shortened: 'VCCB' },
  { name: 'Ngân hàng TMCP Kiên Long', shortened: 'KLB' },
  { name: 'Ngân hàng TMCP Xăng Dầu Petrolimex', shortened: 'PGB' },
  { name: 'Ngân hàng TMCP Sài Gòn Công Thương', shortened: 'SGB' },
  { name: 'Ngân hàng Nông Nghiệp và Phát triển Nông Thôn Việt Nam', shortened: 'AGRIBANK' },
  { name: 'Ngân hàng TMCP Sài Gòn Thương Tín', shortened: 'STB' },
  { name: 'Ngân hàng TMCP Đại Chúng Việt Nam', shortened: 'PVcomBank' },
  { name: 'Ngân hàng Liên Doanh Việt Nga', shortened: 'VRB' },
  { name: 'Ngân hàng TMCP Nam Á', shortened: 'NAMABANK' },
  { name: 'Ngân hàng TNHH Indovina', shortened: 'IVB' },
  { name: 'Ngân hàng TMCP Bưu Điện Liên Việt', shortened: 'LPB' },
  { name: 'Ngân hàng Wooribank', shortened: 'WOO' },
  { name: 'Ngân hàng TMCP Ngoại thương Việt Nam', shortened: 'VCB' },
  { name: 'Ngân hàng IBK - chi nhánh Hà Nội', shortened: 'IBK' },
  { name: 'Ngân hàng TMCP Á Châu', shortened: 'ACB' },
];
